name: Brakeman static analysis

on:
  workflow_call:
    inputs:
      defectdojo_product_name:
        required: true
        type: string
      defectdojo_engagement_name:
        required: true
        type: string
      defectdojo_tags:
        required: true
        type: string

jobs:
  run_brakeman:
    runs-on: ubuntu-latest
    if: (github.actor != 'dependabot[bot]') # Skip any PR created by dependabot to avoid permission issues
    steps:
      - uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          # ruby-version: '3.0' # Not needed with a .ruby-version file
          bundler-cache: false # runs 'bundle install' and caches installed gems automatically
      - name: Install brakeman Gem
        run: |
          gem install brakeman -v 5.2.2
      - name: Create Brakeman JSON Report
        run: |
          brakeman -f json > brakeman.json || exit 0
      - name: Archive Brakeman Report
        uses: actions/upload-artifact@v2
        with:
          name: brakeman-json-report
          path: brakeman.json
      - name: POST Brakeman Report to DefectDojo
        if: github.event_name == 'pull_request' # Only run on pull_request trigger
        run: |
          curl -X POST "http://99.79.10.30:8080/api/v2/reimport-scan/" \
          -H "accept: application/json" \
          -H "Content-Type: multipart/form-data" \
          -H "Authorization: Token ${{ secrets.DEFECTDOJO_API }}" \
          -F "scan_date=$(date +'%Y-%m-%d')" \
          -F "minimum_severity=Info" \
          -F "active=True" \
          -F "verified=True" \
          -F "scan_type=Brakeman Scan" \
          -F "file=@brakeman.json;type=text/json" \
          -F "product_name=${{ inputs.defectdojo_product_name }}" \
          -F "engagement_name=${{ inputs.defectdojo_engagement_name }}" \
          -F "auto_create_context=True" \
          -F "test_title=Brakeman Scan on Pull Request #${{ github.event.number }}" \
          -F "branch_tag=${{ github.head_ref }}" \
          -F "commit_hash=${{ github.sha }}" \
          -F "tags=${{ inputs.defectdojo_tags }}"
      - name: Run Brakeman
        # This step is so that this workflow will fail and inform the developer(s) if there are warnings
        run: |
          brakeman -q --color
