name: Weekly TruffleHog v2 Secrets Analysis

on:
  workflow_call:
    inputs:
      allowed_path:
        required: true
        type: string

jobs:
  weekly_trufflehog_v2_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: TruffleHog Default Branch Scan
        # weekly-scan branch does not limit commit depth so the whole branch history is scanned
        uses: janeapp/trufflehog-actions-scan@weekly-scan
        continue-on-error: true
        with:
          branch: ${{ github.ref }}
          allowed_path: ${{ inputs.allowed_path }}
      - name: Archive TruffleHog v2 report
        uses: actions/upload-artifact@v2
        with:
          name: trufflehog-v2-output_json
          path: trufflehog_v2_output.json
      - name: Push TruffleHog v2 report to DefectDojo
        run: |
          curl -X POST "http://99.79.10.30:8080/api/v2/import-scan/" -H  "accept: application/json" -H  "Content-Type: multipart/form-data" -H  "Authorization: Token ${{ secrets.DEFECTDOJO_API }}" -F "engagement=7" -F "scan_date=$(date +'%Y-%m-%d')" -F "minimum_severity=Info" -F "active=true" -F "verified=true" -F "scan_type=Trufflehog Scan" -F "file=@trufflehog_v2_output.json;type=text/plain" -F "lead=1"
